FROM node:20-alpine AS build

WORKDIR /frontend

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL


COPY ./frontend /frontend
RUN npm install --legacy-peer-deps && npm run build

FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
