version: '3.8'

services:
  api:
    build: .
    ports: 
      - "3000:3000"
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data:
