FROM node:20 AS build

WORKDIR /frontend
COPY ./frontend /frontend
RUN npm install && npm run build

FROM nginx:alpine

COPY --from=build /frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
